"""Subset the Fontsource Nanum fonts to only the characters the game uses.

Usage:
  npm pack @fontsource/nanum-myeongjo @fontsource/nanum-brush-script   # then extract each .tgz
  python3 tools/subset_fonts.py <nanum-myeongjo pkg dir> <nanum-brush-script pkg dir>

Re-run after adding new UI text. Writes assets/fonts/*.woff2 and assets/fonts/fonts.css.
Requires: pip install fonttools brotli
"""
import pathlib, re, sys
from fontTools import subset

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / 'assets' / 'fonts'
SOURCES = [ROOT / 'index.html', *sorted((ROOT / 'js').glob('*.js'))]
FACES = [  # (package dir arg index, css file, family, weight)
    (0, '400.css', 'Nanum Myeongjo', 400),
    (0, '800.css', 'Nanum Myeongjo', 800),
    (1, '400.css', 'Nanum Brush Script', 400),
]


def parse_range(r):
    cps = set()
    for part in r.split(','):
        part = part.strip().upper().removeprefix('U+')
        if '-' in part:
            a, b = part.split('-')
            cps.update(range(int(a, 16), int(b, 16) + 1))
        elif '?' in part:
            cps.update(range(int(part.replace('?', '0'), 16), int(part.replace('?', 'F'), 16) + 1))
        else:
            cps.add(int(part, 16))
    return cps


def main(pkgs):
    text = ''.join(p.read_text(encoding='utf-8') for p in SOURCES)
    used = {ord(c) for c in text} | set(range(0x20, 0x7F))
    OUT.mkdir(parents=True, exist_ok=True)
    for f in OUT.glob('*.woff2'):
        f.unlink()
    css = ['/* Generated by tools/subset_fonts.py — Nanum fonts (SIL OFL 1.1), subset to the game UI text. */']
    total = 0
    for pkg_i, css_name, family, weight in FACES:
        pkg = pathlib.Path(pkgs[pkg_i])
        src_css = (pkg / css_name).read_text()
        for block in re.findall(r'@font-face\s*{[^}]*}', src_css):
            url = re.search(r'url\(\./files/([^)]+\.woff2)\)', block).group(1)
            rng = parse_range(re.search(r'unicode-range:\s*([^;]+);', block).group(1))
            want = sorted(used & rng)
            if not want:
                continue
            opts = subset.Options()
            opts.flavor = 'woff2'
            opts.layout_features = ['*']
            font = subset.load_font(str(pkg / 'files' / url), opts)
            cmap = font.getBestCmap()
            want = [c for c in want if c in cmap]
            if not want:
                continue
            sub = subset.Subsetter(opts)
            sub.populate(unicodes=want)
            sub.subset(font)
            out = OUT / url
            subset.save_font(font, str(out), opts)
            total += out.stat().st_size
            ranges = ','.join(f'U+{c:x}' for c in want)
            css.append(f"@font-face {{ font-family: '{family}'; font-style: normal; font-weight: {weight}; font-display: swap; "
                       f"src: url(./{url}) format('woff2'); unicode-range: {ranges}; }}")
    (OUT / 'fonts.css').write_text('\n'.join(css) + '\n')
    print(f'{len(css) - 1} font files, {total // 1024} KB')


if __name__ == '__main__':
    main(sys.argv[1:])
